# docker-compose.yml
version: "3.8"
services:
    frontend:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app:delegated
            - /app/node_modules
        ports:
            - 5173:5173
        environment:
            - CHOKIDAR_USEPOLLING=true
